"use client";
import Link from "next/link";
import { ChevronRight, Lock, Truck } from "lucide-react";
import Breadcrumbs from "@/components/Breadcrumbs";
import Footer from "@/components/Footer";
import FloatingContacts from "@/components/FloatingContacts";
import { useLanguage } from "@/context/LanguageContext";
const copy = { vi:["Chính Sách & Điều Khoản Dịch Vụ","Chào mừng quý khách đến với maigo79.com. Các chính sách dưới đây bảo vệ quyền lợi khách hàng và đảm bảo vận hành minh bạch.","Vận Chuyển Hành Khách","Quy định về lịch trình, thời gian chờ, hủy chuyến và trách nhiệm các bên.","Bảo Vệ Quyền Riêng Tư","Chính sách thu thập, sử dụng, lưu trữ và bảo mật thông tin cá nhân.","Xem chi tiết quy định"], en:["Service Policies & Terms","These policies protect customers and ensure transparent service operations.","Passenger Transport","Booking confirmation, waiting time, cancellation and responsibility rules.","Privacy Policy","How we collect, use, store and protect personal information.","View policy details"], ko:["서비스 정책 및 약관","아래 정책은 고객 권리와 투명한 서비스 운영을 위한 것입니다.","승객 운송","예약 확인, 대기 시간, 취소 및 책임에 대한 안내입니다.","개인정보 보호","개인정보의 수집, 이용, 보관 및 보호 방침입니다.","자세히 보기"], ru:["Политика и условия","Эти правила защищают клиентов и обеспечивают прозрачность услуг.","Перевозка пассажиров","Правила подтверждения, ожидания, отмены и ответственности.","Конфиденциальность","Сбор, использование, хранение и защита персональных данных.","Подробнее"], zh:["服务政策与条款","以下政策旨在保障客户权益并确保服务运营透明。","乘客运输","有关订单确认、等待时间、取消及双方责任的规定。","隐私政策","个人信息的收集、使用、存储与保护政策。","查看详细条款"] } as const;
export default function PolicyPageClient(){ const {language,t}=useLanguage(); const x=copy[language]; const cards=[[x[2],x[3],"/chinh-sach/van-chuyen-hanh-khach",Truck],[x[4],x[5],"/chinh-sach/bao-ve-quyen-rieng-tu",Lock]] as const; return <main className="min-h-screen bg-white"><Breadcrumbs items={[{name:t.nav.policies}]}/><div className="container mx-auto px-4 md:px-12 lg:px-24 pt-4 md:pt-6 pb-2"><h1 className="text-2xl md:text-3xl font-bold text-gray-900 mb-2">{x[0]}</h1><div className="w-24 h-1 bg-[#174978]"/></div><div className="container mx-auto px-4 md:px-12 lg:px-24 py-4 md:py-6"><p className="text-gray-700 text-base md:text-lg leading-relaxed mb-6">{x[1]}</p><div className="grid grid-cols-1 md:grid-cols-2 gap-5 mb-8">{cards.map(([title,desc,href,Icon])=><Link key={href} href={href} className="bg-slate-50/70 p-5 md:p-6 shadow-xs hover:shadow-md transition-all group"><div className="flex items-start gap-4"><div className="bg-[#EAF2F8] p-3"><Icon className="text-[#174978]" size={28}/></div><div><h2 className="text-lg md:text-xl font-bold text-gray-800 mb-1.5">{title}</h2><p className="text-gray-600 text-xs sm:text-sm mb-3 leading-relaxed">{desc}</p><span className="flex items-center text-[#174978] font-bold text-xs sm:text-sm">{x[6]}<ChevronRight size={16} className="ml-1"/></span></div></div></Link>)}</div></div><Footer/><FloatingContacts/></main> }
